// lib/deal-engine/structuring.ts

import type {
  DealInfrastructureAssessmentOutput,
  DealMonetizationProfileOutput,
  DealSizeBandOutput,
  DealStructureType,
} from "./types";

export interface DealEconomicStructureInput {
  opportunityType: string;
  infrastructureAssessment: DealInfrastructureAssessmentOutput;
  sizeBand: DealSizeBandOutput;
  monetizationProfile: DealMonetizationProfileOutput;
  recurringRevenuePossible?: boolean;
  financingRelevant?: boolean;
}

export interface DealEconomicStructureOutput {
  structureType: DealStructureType;
  primaryTransactionSummary: string;
  tier1Description: string | null;
  tier2Description: string | null;
  tier3Description: string | null;
  counterpartiesNeeded: string[];
  dependencies: string[];
  financingRequired: boolean;
  recurringRevenuePossible: boolean;
  infrastructureGrade: boolean;
  smallDealViable: boolean;
  structureNotes: string | null;
}

function unique(values: string[]): string[] {
  return [...new Set(values)];
}

export function buildDealEconomicStructure(
  input: DealEconomicStructureInput,
): DealEconomicStructureOutput {
  const financingRequired =
    input.financingRelevant === true ||
    input.infrastructureAssessment.financingRelevanceFlag;

  const infrastructureGrade =
    input.infrastructureAssessment.infrastructureFlag &&
    (input.infrastructureAssessment.infrastructureClass === "infrastructure_grade" ||
      input.infrastructureAssessment.infrastructureClass ===
        "portfolio_infrastructure");

  const recurringRevenuePossible =
    input.recurringRevenuePossible === true ||
    input.monetizationProfile.recurringRevenueFlag;

  let structureType: DealStructureType = "single_path";
  const counterpartiesNeeded: string[] = [];
  const dependencies: string[] = [];

  if (infrastructureGrade) {
    structureType = "infrastructure";
    counterpartiesNeeded.push("premium_partner", "customer");
    if (financingRequired) {
      counterpartiesNeeded.push("lender_or_finance_partner");
    }
    dependencies.push("site_validation", "technical_review", "commercial_alignment");
  } else if (
    input.infrastructureAssessment.infrastructureClass === "structured_midmarket" ||
    input.monetizationProfile.stackedMonetizationFlag
  ) {
    structureType = financingRequired ? "financed" : "blended";
    counterpartiesNeeded.push("customer", "execution_partner");
    if (financingRequired) {
      counterpartiesNeeded.push("finance_partner");
    }
    dependencies.push("deal_structuring", "partner_selection");
  } else if (recurringRevenuePossible) {
    structureType = "recurring_service";
    counterpartiesNeeded.push("customer");
    dependencies.push("service_activation");
  }

  const tier1Description =
    input.monetizationProfile.tier1ValueDriver ??
    `Primary transaction anchored to ${input.opportunityType}.`;

  const tier2Description =
    input.monetizationProfile.tier2ValueDriver ??
    (financingRequired
      ? "Adjacent economic layer includes financing or structured commercial support."
      : "Adjacent economic layer includes execution-side monetization.");

  const tier3Description =
    input.monetizationProfile.tier3ValueDriver ??
    (recurringRevenuePossible
      ? "Optimization or recurring revenue layer available post-close."
      : "Tier 3 remains optional and should be explored after execution.");

  const primaryTransactionSummary = infrastructureGrade
    ? "Infrastructure-grade commercial opportunity with premium partner routing and multi-layer monetization."
    : input.infrastructureAssessment.infrastructureFlag
    ? "Structured commercial opportunity with blended execution and monetization paths."
    : "Standard commercial opportunity with scalable routing and layered monetization review.";

  return {
    structureType,
    primaryTransactionSummary,
    tier1Description,
    tier2Description,
    tier3Description,
    counterpartiesNeeded: unique(counterpartiesNeeded),
    dependencies: unique(dependencies),
    financingRequired,
    recurringRevenuePossible,
    infrastructureGrade,
    smallDealViable: input.sizeBand.sizeBand === "micro" || input.sizeBand.sizeBand === "small",
    structureNotes:
      input.monetizationProfile.economicStructureType ??
      "Economic structure generated by embedded deal engine.",
  };
}